name: 'Hello World'
author: alialaa
description: 'Greet someone and record the time'
inputs:
  slack_webhook:  # id of input
    description: 'Slack Webhook'
    required: true
  message:  # id of input
    description: 'Slack Message'
    required: true
runs:
  using: 'docker'
  # image: 'docker://debian:stetch-slim'
  image: 'Dockerfile'
  env:
    ENV_VAR: value
  # entrypoint: 
  args:
    - ${{ inputs.slack_webhook }}
    - ${{ inputs.message}}