name: Node.js CI

on: 
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Log cache hit
      run: echo ${{ steps.cache.outputs.cache-hit }}
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm test -- --coverage
      env:
        CI: true
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: coverage
    - name: Upload to codecov
      run: npx codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Build
      run: npm run build
      if: github.event_name == 'push'
    - name: Archive build
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build
    - name: Deploy
      run: npx surge --project ./build --domain enormous-poison.surge.sh
      env: 
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN}}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN}}
      if: github.event_name == 'push'
  codecov:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: ls -a
      - name: Download Report
        uses: actions/download-artifact@v1
        with:
          name: code-coverage-report
          path: coverage
      - run: ls -a