name: Node.js CI

on: 
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm test -- --coverage
      env:
        CI: true
    - name: Build
      run: npm run build
      if: github.event_name == 'push'
    - name: Deploy
      run: npx surge --project ./build --domain enormous-poison.surge.sh
      env: 
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN}}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN}}
      if: github.event_name == 'push'