name: 'Hello World'
author: alialaa
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'Github Token'
    required: true
  title:
    description: 'Issue Title'
    required: true
  body:
    description: 'Issue Body'
  assignees:
    description: 'Issue Assignees'
    default: []
outputs:
  issue: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'